; Generated by scripts/build/generate_inno_config.py. Do not edit.
#define ProductName "Python Runtime Installer"
#define Publisher "Alune"
#define ProductVersion "0.1.0"
#define AppId "{{779F23D1-372D-4A68-AD18-80C5116A8B50}"
#define RegistryPath "Software\Alune\Python Runtime Installer"
#define PythonVersion "3.13.14"
#define PythonInstallerFilename "python-3.13.14-amd64.exe"
#define OutputBase "python-runtime-installer-0.1.0-windows-x64"
